### ISSUE TITLE
Support color for krew plugins

### ISSUE THREAD

**Issue by bsgrigorov** [kubecolor/kubecolor#192] opened 2024-11-16 01:57 UTC
### Description

Add support for color when running any krew plugin

**Comment by applejag** [comment] 2024-11-18 16:31
If I understand you correctly, then this sounds like a duplicate of https://github.com/kubecolor/kubecolor/issues/113

Closing. Feel free to reopen or create new issue if you disagree

**Closed by applejag** 2024-11-18 16:31 UTC
Labels: duplicate, enhancement
